import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { AppProvider } from "./context/productContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
          <AppProvider>
            {children}
          </AppProvider>
          
        <Footer />
      </body>
    </html>
  );
}
